name: geo_pattern
version: 0.0.1
author: Justin Fagnani <justin@fagnani.com>
description: A Dart port of the geo_pattern library for creating tiling SVG patterns from strings.
homepage: https://github.com/justinfagnani/geo_pattern.dart
dependencies:
  colors: any
  crypto: '>=0.8.0 <0.10.0'
  quiver: '>=0.17.0 <0.19.0'
dev_dependencies:
  unittest: '>=0.10.0 <0.12.0'
